name: Build and deploy .NET 8 application to Function App guid-api
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "src/static-site/**"
env:
  AZURE_FUNCTIONAPP_NAME_EU1: jvguidapi-prd-weu-app
  AZURE_FUNCTIONAPP_NAME_US1: jvguidapi-prd-wus-app
  AZURE_FUNCTIONAPP_NAME_AU1: jvguidapi-prd-aus-app
  AZURE_RESOURCEGROUP_NAME_EU1: jvguidapi-prd-weu
  AZURE_RESOURCEGROUP_NAME_US1: jvguidapi-prd-wus
  AZURE_RESOURCEGROUP_NAME_AU1: jvguidapi-prd-aus
  AZURE_STATIC_SITE_STORAGE_ACCOUNT: "jvguidapistaticprdweu.blob.core.windows.net"
  AZURE_FUNCTIONAPP_NAME_TEST_EU1: jvguidapi-tst-weu-app
  AZURE_FUNCTIONAPP_NAME_TEST_US1: jvguidapi-tst-wus-app
  AZURE_FUNCTIONAPP_NAME_TEST_AU1: jvguidapi-tst-aus-app
  AZURE_RESOURCEGROUP_NAME_TEST_EU1: jvguidapi-tst-weu
  AZURE_RESOURCEGROUP_NAME_TEST_US1: jvguidapi-tst-wus
  AZURE_RESOURCEGROUP_NAME_TEST_AU1: jvguidapi-tst-aus
  AZURE_STATIC_SITE_STORAGE_ACCOUNT_TEST: "jvguidapistatictstweu.blob.core.windows.net"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.x
  WORKING_DIRECTORY: src
  DOTNET_CORE_VERSION_INPROC: ""
jobs:
  compile-functions-app:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core ${{ env.DOTNET_CORE_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Setup .NET Core (for inproc extensions)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION_INPROC }}

      - name: Dotnet restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Dotnet build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Dotnet publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"

      - name: "Zip published content"
        uses: vimtor/action-zip@v1
        with:
          files: ./output/
          recursive: true
          dest: artifact.zip

      - name: Publish Functions artifact
        uses: actions/upload-artifact@v4
        with:
          name: functions-artifact
          path: artifact.zip

  publish-bicep:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-templates
          path: deployment/infrastructure/

  infrastructure-test:
    needs: publish-bicep
    runs-on: ubuntu-24.04
    environment: Test
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-templates
          path: ./infrastructure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEV }}

      - name: Deploy Infrastructure
        id: deployinfrastructure
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az deployment sub create --location WestEurope --template-file ./infrastructure/main.bicep --parameters ./infrastructure/parameters.test.json

  deploy-functions-test:
    needs: [compile-functions-app, infrastructure-test]
    runs-on: ubuntu-24.04
    environment: Test
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: functions-artifact
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEV }}

      - name: "Deploy web app - EU1"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_TEST_EU1 }}
          package: "artifact.zip"

      - name: "Deploy web app - US1"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_TEST_US1 }}
          package: "artifact.zip"

      - name: "Deploy web app - AU1"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_TEST_AU1 }}
          package: "artifact.zip"

  infrastructure-production:
    needs: [publish-bicep, deploy-functions-test]
    runs-on: ubuntu-24.04
    environment: Production
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-templates
          path: ./infrastructure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEV }}

      - name: Deploy Infrastructure
        id: deployinfrastructure
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az deployment sub create --location WestEurope --template-file ./infrastructure/main.bicep --parameters ./infrastructure/parameters.json

  deploy-functions-production:
    needs: [compile-functions-app, infrastructure-production]
    runs-on: ubuntu-24.04
    environment: Production
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: functions-artifact
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEV }}

      - name: "Deploy web app - EU1"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_EU1 }}
          package: "artifact.zip"

      - name: "Deploy web app - US1"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_US1 }}
          package: "artifact.zip"

      - name: "Deploy web app - AU1"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_AU1 }}
          package: "artifact.zip"
