name: Deploy static site
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/static-site/**"

env:
  AZURE_STORAGE_ACCOUNT_NAME: jvguidapistaticprdweusa
  AZURE_STORAGE_ACCOUNT_NAME_TEST: jvguidapistatictstweusa
  STATIC_FILES_WORKING_DIRECTORY: ./src/static-site/

jobs:
  publish-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bicep-templates
          path: deployment/infrastructure/

  infrastructure-test:
    needs: publish-bicep
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: bicep-templates
          path: ./infrastructure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEV }}

      - name: Deploy Infrastructure
        id: deployinfrastructure
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az deployment sub create --location WestEurope --template-file ./infrastructure/main-static-site.bicep --parameters ./infrastructure/parameters.test.json

  deploy-static-site-test:
    needs: infrastructure-test
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEV }}
      - name: Configure static site hosting
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob service-properties update --account-name ${{ env.AZURE_STORAGE_ACCOUNT_NAME_TEST }} --static-website --index-document index.html --404-document 404.html
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ env.AZURE_STORAGE_ACCOUNT_NAME_TEST }} --auth-mode key -d '$web' -s ${{ env.STATIC_FILES_WORKING_DIRECTORY }}

  infrastructure-production:
    needs: [publish-bicep, deploy-static-site-test]
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: bicep-templates
          path: ./infrastructure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEV }}

      - name: Deploy Infrastructure
        id: deployinfrastructure
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az deployment sub create --location WestEurope --template-file ./infrastructure/main-static-site.bicep --parameters ./infrastructure/parameters.json

  deploy-static-site-production:
    needs: infrastructure-production
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEV }}
      - name: Configure static site hosting
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob service-properties update --account-name ${{ env.AZURE_STORAGE_ACCOUNT_NAME }} --static-website --index-document index.html --404-document 404.html
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ env.AZURE_STORAGE_ACCOUNT_NAME }} --auth-mode key -d '$web' -s ${{ env.STATIC_FILES_WORKING_DIRECTORY }}
